package com.google.android.gms.measurement.internal;

import android.content.Context;
import com.google.android.exoplayer2.C;
import com.google.android.exoplayer2.audio.AacUtil;
import com.google.android.gms.internal.measurement.zzmf;
import com.google.firebase.iid.ServiceStarter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import org.apache.commons.lang3.time.DateUtils;

/* compiled from: com.google.android.gms:play-services-measurement-impl@@18.0.0 */
/* loaded from: classes2.dex */
public final class zzas {
    public static zzej<Long> zzaa;
    public static zzej<Integer> zzab;
    public static zzej<Long> zzac;
    public static zzej<Integer> zzad;
    public static zzej<Integer> zzae;
    public static zzej<Integer> zzaf;
    public static zzej<Integer> zzag;
    public static zzej<Integer> zzah;
    public static zzej<Long> zzai;
    public static zzej<Boolean> zzaj;
    public static zzej<String> zzak;
    public static zzej<Long> zzal;
    public static zzej<Integer> zzam;
    public static zzej<Double> zzan;
    public static zzej<Integer> zzao;
    public static zzej<Integer> zzap;
    public static zzej<Boolean> zzaq;
    public static zzej<Boolean> zzar;
    public static zzej<Boolean> zzas;
    public static zzej<Boolean> zzat;
    public static zzej<Boolean> zzau;
    public static zzej<Boolean> zzav;
    public static zzej<Boolean> zzaw;
    public static zzej<Boolean> zzax;
    public static zzej<Boolean> zzay;
    public static zzej<Boolean> zzaz;
    public static zzej<Boolean> zzba;
    public static zzej<Boolean> zzbb;
    public static zzej<Boolean> zzbc;
    public static zzej<Boolean> zzbd;
    public static zzej<Boolean> zzbe;
    public static zzej<Boolean> zzbf;
    public static zzej<Boolean> zzbg;
    public static zzej<Boolean> zzbh;
    public static zzej<Boolean> zzbi;
    public static zzej<Boolean> zzbj;
    public static zzej<Boolean> zzbk;
    public static zzej<Boolean> zzbl;
    public static zzej<Boolean> zzbm;
    public static zzej<Boolean> zzbn;
    public static zzej<Boolean> zzbo;
    public static zzej<Boolean> zzbp;
    public static zzej<Boolean> zzbq;
    public static zzej<Boolean> zzbr;
    public static zzej<Boolean> zzbs;
    public static zzej<Boolean> zzbt;
    public static zzej<Boolean> zzbu;
    public static zzej<Boolean> zzbv;
    public static zzej<Boolean> zzbw;
    public static zzej<Boolean> zzbx;
    public static zzej<Boolean> zzby;
    public static zzej<Boolean> zzbz;
    public static zzej<Long> zzc;
    public static zzej<Boolean> zzca;
    public static zzej<Boolean> zzcb;
    public static zzej<Boolean> zzcc;
    public static zzej<Long> zzcd;
    public static zzej<Boolean> zzce;
    public static zzej<Boolean> zzcf;
    public static zzej<Boolean> zzcg;
    public static zzej<Boolean> zzch;
    public static zzej<Boolean> zzci;
    public static zzej<Integer> zzcj;
    public static zzej<Boolean> zzck;
    public static zzej<Boolean> zzcl;
    public static zzej<Boolean> zzcm;
    public static zzej<Boolean> zzcn;
    private static zzej<Boolean> zzcq;
    public static zzej<String> zzd;
    public static zzej<String> zze;
    public static zzej<Integer> zzf;
    public static zzej<Integer> zzg;
    public static zzej<Integer> zzh;
    public static zzej<Integer> zzi;
    public static zzej<Integer> zzj;
    public static zzej<Integer> zzk;
    public static zzej<Integer> zzl;
    public static zzej<Integer> zzm;
    public static zzej<Integer> zzn;
    public static zzej<Integer> zzo;
    public static zzej<String> zzp;
    public static zzej<Long> zzq;
    public static zzej<Long> zzr;
    public static zzej<Long> zzs;
    public static zzej<Long> zzt;
    public static zzej<Long> zzu;
    public static zzej<Long> zzv;
    public static zzej<Long> zzw;
    public static zzej<Long> zzx;
    public static zzej<Long> zzy;
    public static zzej<Long> zzz;
    private static List<zzej<?>> zzco = Collections.synchronizedList(new ArrayList());
    private static Set<zzej<?>> zzcp = Collections.synchronizedSet(new HashSet());
    public static zzej<Long> zza = zza("measurement.ad_id_cache_time", 10000L, 10000L, zzav.zza);
    public static zzej<Long> zzb = zza("measurement.monitoring.sample_period_millis", 86400000L, 86400000L, zzau.zza);

    public static Map<String, String> zza(Context context) {
        com.google.android.gms.internal.measurement.zzct zzctVarZza = com.google.android.gms.internal.measurement.zzct.zza(context.getContentResolver(), com.google.android.gms.internal.measurement.zzde.zza("com.google.android.gms.measurement"));
        return zzctVarZza == null ? Collections.emptyMap() : zzctVarZza.zza();
    }

    private static <V> zzej<V> zza(String str, V v, V v2, zzeh<V> zzehVar) {
        zzej<V> zzejVar = new zzej<>(str, v, v2, zzehVar);
        zzco.add(zzejVar);
        return zzejVar;
    }

    static final /* synthetic */ Long zzci() {
        zzw zzwVar = zzeg.zza;
        return Long.valueOf(zzmf.zzc());
    }

    static {
        Long lValueOf = Long.valueOf(DateUtils.MILLIS_PER_HOUR);
        zzc = zza("measurement.config.cache_time", 86400000L, lValueOf, zzbh.zza);
        zzd = zza("measurement.config.url_scheme", "https", "https", zzbq.zza);
        zze = zza("measurement.config.url_authority", "app-measurement.com", "app-measurement.com", zzcd.zza);
        zzf = zza("measurement.upload.max_bundles", 100, 100, zzcm.zza);
        zzg = zza("measurement.upload.max_batch_size", 65536, 65536, zzcz.zza);
        zzh = zza("measurement.upload.max_bundle_size", 65536, 65536, zzdi.zza);
        zzi = zza("measurement.upload.max_events_per_bundle", 1000, 1000, zzdv.zza);
        Integer numValueOf = Integer.valueOf(AacUtil.AAC_LC_MAX_RATE_BYTES_PER_SECOND);
        zzj = zza("measurement.upload.max_events_per_day", numValueOf, numValueOf, zzef.zza);
        zzk = zza("measurement.upload.max_error_events_per_day", 1000, 1000, zzax.zza);
        zzl = zza("measurement.upload.max_public_events_per_day", 50000, 50000, zzaw.zza);
        zzm = zza("measurement.upload.max_conversions_per_day", 10000, 10000, zzaz.zza);
        zzn = zza("measurement.upload.max_realtime_events_per_day", 10, 10, zzay.zza);
        zzo = zza("measurement.store.max_stored_events_per_app", numValueOf, numValueOf, zzbb.zza);
        zzp = zza("measurement.upload.url", "https://app-measurement.com/a", "https://app-measurement.com/a", zzba.zza);
        zzq = zza("measurement.upload.backoff_period", 43200000L, 43200000L, zzbd.zza);
        zzr = zza("measurement.upload.window_interval", lValueOf, lValueOf, zzbc.zza);
        zzs = zza("measurement.upload.interval", lValueOf, lValueOf, zzbf.zza);
        zzt = zza("measurement.upload.realtime_upload_interval", 10000L, 10000L, zzbe.zza);
        zzu = zza("measurement.upload.debug_upload_interval", 1000L, 1000L, zzbg.zza);
        zzv = zza("measurement.upload.minimum_delay", 500L, 500L, zzbj.zza);
        zzw = zza("measurement.alarm_manager.minimum_interval", 60000L, 60000L, zzbi.zza);
        zzx = zza("measurement.upload.stale_data_deletion_interval", 86400000L, 86400000L, zzbl.zza);
        zzy = zza("measurement.upload.refresh_blacklisted_config_interval", 604800000L, 604800000L, zzbk.zza);
        Long lValueOf2 = Long.valueOf(C.DEFAULT_SEEK_FORWARD_INCREMENT_MS);
        zzz = zza("measurement.upload.initial_upload_delay_time", lValueOf2, lValueOf2, zzbn.zza);
        zzaa = zza("measurement.upload.retry_time", 1800000L, 1800000L, zzbm.zza);
        zzab = zza("measurement.upload.retry_count", 6, 6, zzbp.zza);
        zzac = zza("measurement.upload.max_queue_time", 2419200000L, 2419200000L, zzbo.zza);
        zzad = zza("measurement.lifetimevalue.max_currency_tracked", 4, 4, zzbr.zza);
        zzae = zza("measurement.audience.filter_result_max_count", 200, 200, zzbt.zza);
        zzaf = zza("measurement.upload.max_public_user_properties", 25, 25, null);
        Integer numValueOf2 = Integer.valueOf(ServiceStarter.ERROR_UNKNOWN);
        zzag = zza("measurement.upload.max_event_name_cardinality", numValueOf2, numValueOf2, null);
        zzah = zza("measurement.upload.max_public_event_params", 25, 25, null);
        zzai = zza("measurement.service_client.idle_disconnect_millis", 5000L, 5000L, zzbs.zza);
        zzaj = zza("measurement.test.boolean_flag", false, false, zzbv.zza);
        zzak = zza("measurement.test.string_flag", "---", "---", zzbu.zza);
        zzal = zza("measurement.test.long_flag", -1L, -1L, zzbx.zza);
        zzam = zza("measurement.test.int_flag", -2, -2, zzbw.zza);
        Double dValueOf = Double.valueOf(-3.0d);
        zzan = zza("measurement.test.double_flag", dValueOf, dValueOf, zzbz.zza);
        zzao = zza("measurement.experiment.max_ids", 50, 50, zzby.zza);
        zzap = zza("measurement.max_bundles_per_iteration", 100, 100, zzcb.zza);
        zzaq = zza("measurement.validation.internal_limits_internal_event_params", false, false, zzca.zza);
        zzar = zza("measurement.collection.firebase_global_collection_flag_enabled", true, true, zzcc.zza);
        zzas = zza("measurement.collection.efficient_engagement_reporting_enabled_2", true, true, zzcf.zza);
        zzat = zza("measurement.collection.redundant_engagement_removal_enabled", false, false, zzce.zza);
        zzau = zza("measurement.client.freeride_engagement_fix", true, true, zzch.zza);
        zzav = zza("measurement.collection.log_event_and_bundle_v2", true, true, zzcg.zza);
        zzaw = zza("measurement.quality.checksum", false, false, null);
        zzax = zza("measurement.sdk.dynamite.allow_remote_dynamite3", true, true, zzcj.zza);
        zzay = zza("measurement.sdk.collection.validate_param_names_alphabetical", true, true, zzci.zza);
        zzaz = zza("measurement.audience.use_bundle_end_timestamp_for_non_sequence_property_filters", false, false, zzcl.zza);
        zzba = zza("measurement.audience.refresh_event_count_filters_timestamp", false, false, zzck.zza);
        zzbb = zza("measurement.audience.use_bundle_timestamp_for_event_count_filters", false, false, zzcn.zza);
        zzbc = zza("measurement.sdk.collection.retrieve_deeplink_from_bow_2", true, true, zzcp.zza);
        zzbd = zza("measurement.sdk.collection.last_deep_link_referrer2", true, true, zzco.zza);
        zzbe = zza("measurement.sdk.collection.last_deep_link_referrer_campaign2", false, false, zzcr.zza);
        zzbf = zza("measurement.sdk.collection.last_gclid_from_referrer2", false, false, zzcq.zza);
        zzbg = zza("measurement.sdk.collection.enable_extend_user_property_size", true, true, zzct.zza);
        zzbh = zza("measurement.upload.file_lock_state_check", false, false, zzcs.zza);
        zzbi = zza("measurement.ga.ga_app_id", false, false, zzcv.zza);
        zzbj = zza("measurement.lifecycle.app_in_background_parameter", false, false, zzcu.zza);
        zzbk = zza("measurement.integration.disable_firebase_instance_id", false, false, zzcx.zza);
        zzbl = zza("measurement.lifecycle.app_backgrounded_engagement", false, false, zzcw.zza);
        zzbm = zza("measurement.collection.service.update_with_analytics_fix", false, false, zzcy.zza);
        zzbn = zza("measurement.service.use_appinfo_modified", false, false, zzdb.zza);
        zzbo = zza("measurement.client.firebase_feature_rollout.v1.enable", true, true, zzda.zza);
        zzbp = zza("measurement.client.sessions.check_on_reset_and_enable2", true, true, zzdd.zza);
        zzbq = zza("measurement.scheduler.task_thread.cleanup_on_exit", false, false, zzdc.zza);
        zzbr = zza("measurement.upload.file_truncate_fix", false, false, zzdf.zza);
        zzbs = zza("measurement.sdk.referrer.delayed_install_referrer_api", false, false, zzde.zza);
        zzbt = zza("measurement.sdk.screen.disabling_automatic_reporting", true, true, zzdh.zza);
        zzbu = zza("measurement.sdk.screen.manual_screen_view_logging", true, true, zzdg.zza);
        zzcq = zza("measurement.collection.synthetic_data_mitigation", false, false, zzdj.zza);
        zzbv = zza("measurement.service.configurable_service_limits", true, true, zzdl.zza);
        zzbw = zza("measurement.client.configurable_service_limits", true, true, zzdk.zza);
        zzbx = zza("measurement.androidId.delete_feature", true, true, zzdn.zza);
        zzby = zza("measurement.client.global_params", true, true, zzdm.zza);
        zzbz = zza("measurement.service.global_params", true, true, zzdp.zza);
        zzca = zza("measurement.service.global_params_in_payload", true, true, zzdo.zza);
        zzcb = zza("measurement.client.string_reader", true, true, zzdr.zza);
        zzcc = zza("measurement.sdk.attribution.cache", true, true, zzdq.zza);
        zzcd = zza("measurement.sdk.attribution.cache.ttl", 604800000L, 604800000L, zzdt.zza);
        zzce = zza("measurement.service.database_return_empty_collection", true, true, zzds.zza);
        zzcf = zza("measurement.service.ssaid_removal", true, true, zzdu.zza);
        zzcg = zza("measurement.client.consent_state_v1", true, true, zzdx.zza);
        zzch = zza("measurement.client.3p_consent_state_v1", true, true, zzdw.zza);
        zzci = zza("measurement.service.consent_state_v1_W36", false, false, zzdz.zza);
        zzcj = zza("measurement.service.storage_consent_support_version", 203590, 203590, zzdy.zza);
        zzck = zza("measurement.client.ad_impression", true, true, zzeb.zza);
        zzcl = zza("measurement.service.ad_impression", true, true, zzea.zza);
        zzcm = zza("measurement.service.separate_public_internal_event_blacklisting", true, true, zzed.zza);
        zzcn = zza("measurement.service.directly_maybe_log_error_events", false, false, zzec.zza);
    }
}
